name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest ruff
      
      - name: Lint
        run: |
          ruff check .

      - name: Run tests
        run: |
          python -m pytest -q

      - name: Lint
        run: |
          ruff check .